services:
  ctla:
    build:
      context: .
      dockerfile: Dockerfile
      target: cron
    restart: unless-stopped
    volumes:
      - ./ctla_config.json:/app/ctla_config.json
      - ./client_secrets.json:/app/client_secrets.json
      - ./youtube_credentials.json:/app/youtube_credentials.json